language: node_js
node_js:
- 7.9.0
before_script:
- mkdir conf
- cp ci/lambda-config.js conf
- npm install -g gulp
- npm install
script: gulp deploy
sudo: false
notifications:
  slack:
    secure: IW61vnTenbyQ9Et0ToLiM87W3/LTSlnEcRL2U8VKlR2PjDEyOjSNOsDvqoqVsx9tMLEFaLhoTL6VB7e7gub3WxmECW5vnJowuInUQWoga+P4sEfs9Bjth04jCch2YQCkYEvbEBbmn/s1y4GKXQ/T6k1nJcAdg8PbpxOk7DZmpWD0x7LwPyU9Mol+mRQXgxxj/EtZqycAbNYctF5JnOBR1mMHS+BW68YLse5VFvGf3ktcFlDcEXQF0g1P9rnSjSv54EJpbYWVlJN3g8DwsQm7kBuo5UurQRmNshaCcQ30NdWTF4qcMEtTaSx40TE+1yYQ6OYypH3b505vprvMjlZTjUEEL8ZVNwHR3LFhQlfljKwJm4bzcU3q4zKDOCROw/d1HW/sxlPb1U3WKxnoa4XIcRx1IpxuZqz57TmPmZjiFoz22gKoiA27k7JxKSUy9Hw4u9mp1BUEVTqjTG4352Gk5yjmiDDiU+P1n9EP7DlmLlNkefAJ9boGAnPs2JHIC8M3lsktrMxkzZLflKziAmRpxPBv/USL+X71FjYIdUKkwvvpuceHXepSXayGaGrf1uK6KMiC/vtDNHZ6q/GHaTgw86x4xcFyb3cP/jvKkhQC6WPm1qh07t6w8roAxnveJ1G8Sml6yhZy5Otzx0SWcvWyJuYrtQrTkz7CenIF1TBbXgY=
