language: node_js
node_js:
  - "7.9.0"
before_script:
  - mkdir conf
  - cp ci/lambda-config.js conf
  - npm install -g gulp
  - npm install
script: gulp deploy
sudo: false
notifications:
  slack:
    secure: reFYckyDdAu5q7zIviv5gNGhPQnvCtOgsiyXWnZpMCQHpS59K8n+4/eydCrycxWRL0QZTg35hy/yLDACNT46loIjBG6l7BS4zR7fSpDf/lgF+ICuueho8127r1jeNTclIQ99YaIUPJqfvjBmAlKc8XpTmq7cuBk0eGgS8V18nJgELbrBIxbwIoH0DiSWIBAFuAj28L4wIeXWjt4BjdXx7uKenblXYBALahiPsbLTQ1LD6ok9gQvhWWqWXu4sK/9lkESd4gicHsrGhVxkedSVS5FL4aQEq/XKDS0DsNVUiKc7AJWnPfsht1pBKL09Tw+pyvYjifhoaClREGvxpp+odVzAmYNpltLj3aPHej1qI4LWCmn/ts68eB9GkEeKbMwP7HpPczzuVXHPkU10xvKtVHKkcqc8Jq31Q+y3W8CCy0af0wyv3m3DoQc98MNhMZE0v3t5w4Tyq1BrDCL5S74Ekng97DdN9sgkyoEWBctWSxBRkCW0MDA5BumBXq2b+RY3yT3rFIfyGOsBV7fRSdua53J0ro02+VFmrf5cOWGIAROSx4ufF5lPEXwyPOTCO+31Y/HNC0rhAPphfVrxLEmRugzJDIzgvIzWe0i/Uo3Ey0qaV99z75w2wEHNsxR/R6DwCJzhc4iJXJsfH3xAOmyTvi8azZgH/xXagiV8zibofZE=
